name: Ingest YouTube Playlist Data to Port using API

on:
  workflow_dispatch:

jobs:
  fetch-and-ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Authenticate with GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: echo "Authenticated with GitHub using the Personal Access Token."

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch YouTube Playlist Data
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
        run: |
          # Fetch playlist items (videos) from the YouTube API and save to data.json
          curl -X GET "https://www.googleapis.com/youtube/v3/playlistItems?playlistId=${PLAYLIST_ID}&part=snippet,contentDetails,statistics&key=${YOUTUBE_API_KEY}&maxResults=50" > data.json

      - name: Process YouTube Data
        run: |
          # Parse data.json and extract required fields for each video
          cat data.json | jq -c '.items[] | {
            identifier: .contentDetails.videoId,
            title: .snippet.title,
            properties: {
              id: .contentDetails.videoId,
              title: .snippet.title,
              description: .snippet.description,
              channel_id: .snippet.channelId,
              channel_title: .snippet.channelTitle,
              published_at: .snippet.publishedAt,
              view_count: .statistics.viewCount,
              like_count: .statistics.likeCount,
              comment_count: .statistics.commentCount,
              duration: .contentDetails.duration
            }
          }' > processed_data.json

      - name: Ingest Data to Port
        env:
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
        run: |
          # Loop through each video entry in processed_data.json and ingest to Port
          while IFS= read -r video; do
            identifier=$(echo "$video" | jq -r '.identifier')
            title=$(echo "$video" | jq -r '.title')
            properties=$(echo "$video" | jq -c '.properties')

            echo "Ingesting video with ID: $identifier"

            # Use Port GitHub Action to ingest each video's data
            gh workflow run - uses: port-labs/port-github-action@v1 \
              with:
                clientId: ${{ secrets.PORT_CLIENT_ID }}
                clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
                baseUrl: https://api.getport.io
                operation: UPSERT
                identifier: "$identifier"
                title: "$title"
                blueprint: playlist
                properties: "$properties"
          done < processed_data.json
