name: YouTube Playlist to Port Ingestion

on:
  #push:
    #branches: [main]
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Includes the blueprint identifier, and the action's run id
      playlist_id:
        required: true
        description: The playlist id
        type: string

jobs:
  ingest-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch Playlist
        env:
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          # Set the playlist ID and blueprint ID
          PLAYLIST_ID=${{ inputs.playlist_id }}
          blueprint_id=${{ fromJson(inputs.port_context).blueprint }}

          # Step 1: Fetch Playlist Videos from YouTube API
          nextPageToken=""
          while true; do
              # Fetch videos in the playlist (one page at a time)
              response=$(curl -s "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,contentDetails&playlistId=$PLAYLIST_ID&maxResults=50&pageToken=$nextPageToken&key=$YOUTUBE_API_KEY")

              # Parse and iterate over each video
              echo "$response" | jq -c '.items[]' | while read -r item; do
                  video_id=$(echo "$item" | jq -r '.contentDetails.videoId')
                  title=$(echo "$item" | jq -r '.snippet.title')
                  description=$(echo "$item" | jq -r '.snippet.description')
                  published_at=$(echo "$item" | jq -r '.contentDetails.videoPublishedAt')
                  channel_id=$(echo "$item" | jq -r '.snippet.channelId')
                  channel_title=$(echo "$item" | jq -r '.snippet.channelTitle')

                  # Step 2: Fetch Additional Video Details
                  video_details=$(curl -s "https://www.googleapis.com/youtube/v3/videos?part=statistics,contentDetails&id=$video_id&key=$YOUTUBE_API_KEY")
                  duration=$(echo "$video_details" | jq -r '.items[0].contentDetails.duration')
                  view_count=$(echo "$video_details" | jq -r '.items[0].statistics.viewCount | tonumber')
                  like_count=$(echo "$video_details" | jq -r '.items[0].statistics.likeCount | tonumber')
                  comment_count=$(echo "$video_details" | jq -r '.items[0].statistics.commentCount | tonumber')

                  # Prepare data for Port API ingestion
                  video_data=$(jq -n --arg identifier "$video_id" \
                                 --arg title "$title" \
                                 --arg id "$video_id" \
                                 --arg description "$description" \
                                 --arg published_at "$published_at" \
                                 --arg channel_id "$channel_id" \
                                 --arg channel_title "$channel_title" \
                                 --arg duration "$duration" \
                                 --arg view_count "$view_count" \
                                 --arg like_count "$like_count" \
                                 --arg comment_count "$comment_count" \
                                 '{
                                     identifier: $identifier,
                                     title: $title,
                                     properties: {
                                         id: $id,
                                         description: $description,
                                         title: $title,
                                         published_at: $published_at,
                                         channel_id: $channel_id,
                                         channel_title: $channel_title,
                                         duration: $duration,
                                         view_count: $view_count,
                                         like_count: $like_count,
                                         comment_count: $comment_count
                                     },
                                     relations: {
                      
                                     }
                                 }')
                  videos_data="$videos_data$video_data"

              done

              # Check if there is another page of results
              nextPageToken=$(echo "$response" | jq -r '.nextPageToken')
              [ "$nextPageToken" == "null" ] && break
          done

          echo "::set-output name=videos_data::$videos_data"

      - name: Ingest data to Port
        id: ingest_data
        uses: port-labs/port-github-action@v1
        with:
          identifier: "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].id }}"
          title: "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].title }}"
          blueprint: ${{fromJson(inputs.port_context).blueprint}}
          properties: |-
            {
              "status": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].status }}",
              "url": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].self }}",
              "urgency": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].urgency }}",
              "responder": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].assignments[0].assignee.summary}}",
              "escalation_policy": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].escalation_policy.summary }}",
              "created_at": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].created_at }}",
              "updated_at": "${{ fromJson(steps.acknowledge_incident.outputs.response).incidents[0].updated_at }}"
            }
          relations: "${{ toJson(fromJson(inputs.port_context).relations) }}"
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: UPSERT
          runId: ${{fromJson(inputs.port_context).run_id}}
